apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-cluster-aashishsawant

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-develop-deployment
  namespace: kubernetes-cluster-aashishsawant
  labels:
    app: nagp-develop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nagp-develop
  template:
    metadata:
      name:  nagp-develop-pod
      labels:
        app: nagp-develop
    spec:
      containers:
      - name: nagp-develop-container
        image: aashishsawant/i-aashishsawant-develop:latest
        envFrom: 
        - configMapRef:
            name: nagp-develop-config
        - secretRef:
            name: nagp-develop-secret

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nagp-develop-config
  namespace: kubernetes-cluster-aashishsawant
  labels:
    app: nagp-develop
data:
  AppConfigUrl: "https://test.io/"
  AppConfigEnvironment: "Production"

---
apiVersion: v1
kind: Secret
metadata:
  name: nagp-develop-secret
  namespace: kubernetes-cluster-aashishsawant
  labels:
    app: nagp-develop
data:
  Key: YWFzaGlzaC5zYXdhbnRAbmFnYXJyby5jb20=
  Vault: VGhpc0BQYXNzd29yZA==
type: Opaque            