apiVersion: v1
kind: Service
metadata:
  name: nagp-develop-service
  namespace: kubernetes-cluster-aashishsawant
spec:
  selector:
    app: nagp-develop
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31500
  type: LoadBalancer


